version: '2' 
services:
  spring:
    build: ./spring-boot-app
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - node
    environment:
      - APP_NODE_URL=http://node:8081/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/demodb
      - SPRING_DATASOURCE_USERNAME=demouser
      - SPRING_DATASOURCE_PASSWORD=DemoPa$$

  postgres:
    image: 'postgres:10-alpine'
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=demodb
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=DemoPa$$

  node:
    build: ./node-app
    restart: always
    ports:
      - 8081:8081

